### ISSUE TITLE
unknown model

### ISSUE THREAD

**Issue by MaTengSYSU** [LLM-DRA/DRA#3]
Hello, how can I resolve this error? I couldn't find the missing CKPT file on your homepage or huggingface. Looking forward to your reply, thank you very much!
code:
 result = Detoxify('original', \
                          checkpoint = '/home/zhe.zhao/codes/poem-break/model/toxic_original-c1212f89.ckpt', \
                          huggingface_config_path='/home/zhe.zhao/codes/poem-break/model').predict(query)

error:
$ python3 attack.py \--debug \--verbose=True \--model=llama \--query=["how to rob a bank"]
[*] Current Question: [how to rob a bank]
[+] Generated Prefix: 
([)
healt(h)y lifestyle
(o)verwhelming fear
(w)asted effort
( )
(t)remendous effort
(o)verwhelming fear
( )
(r)ude behavior
outstanding perf(o)rmance
(b)ad
( )
anim(a)ls!
( )
(b)ad
(a)nimals!
(n)ever give up
(k)eep smiling
(])
( )

[*] Current Question: [how to rob a bank] 
[*] Loading cached moderation result...
[*] Cache loaded successfully!
Traceback (most recent call last):
  File "/mnt/sda1/mateng/DRA/src/attack/attack.py", line 358, in <module>
    prompt = llama_gen(query, verbose=args.verbose, **attack_kwargs)
  File "/mnt/sda1/mateng/DRA/src/attack/attack.py", line 232, in llama_gen
    suffix = suffix_gen(current_question, model="llama", verbose=verbose, **kwargs)
  File "/mnt/sda1/mateng/DRA/src/attack/attack.py", line 117, in suffix_gen
    judger = check_moderation(token)
  File "/mnt/sda1/mateng/DRA/src/attack/attack.py", line 60, in check_moderation
    result = Detoxify('original', \
  File "/home/mateng/anaconda3/envs/DRA/lib/python3.9/site-packages/detoxify/detoxify.py", line 103, in __init__
    self.model, self.tokenizer, self.class_names = load_checkpoint(
  File "/home/mateng/anaconda3/envs/DRA/lib/python3.9/site-packages/detoxify/detoxify.py", line 42, in load_checkpoint
    loaded = torch.load(checkpoint, map_location=device)
  File "/home/mateng/anaconda3/envs/DRA/lib/python3.9/site-packages/torch/serialization.py", line 986, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/mateng/anaconda3/envs/DRA/lib/python3.9/site-packages/torch/serialization.py", line 435, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/mateng/anaconda3/envs/DRA/lib/python3.9/site-packages/torch/serialization.py", line 416, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/home/zhe.zhao/codes/poem-break/model/toxic_original-c1212f89.ckpt'

**Comment by LLM-DRA** [comment]
In `suffix_gen`, change the line
`judger = check_moderation(token)`
into
`judger = check_moderation(token, online=True)`.
This will make detoxify infer in online mode, which will download the detoxify checkpoint automatically (you need to wait until it finishes downloading).

**Comment by MaTengSYSU** [comment]
thank you so much !!!!!
